<a href="https://colab.research.google.com/github/beth0313/Ejercicio_5_python/blob/main/Ejercicio_6_TTL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Proceso ETL con dataset público (Iris Dataset)
En el contexto del análisis de datos, una de las tareas más comunes es realizar procesos de ETL ***(Extract, Transform, Load)*** sobre datasets en formato CSV.
Para este ejercicio, el aprendiz deberá trabajar en Google Colab con el dataset Iris, el cual es uno de los datasets más utilizados en ciencia de datos y contiene información de flores con variables numéricas y categóricas.
###El dataset puede ser consumido directamente desde la siguiente URL: ***[Dataset Iris](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data)***


##Objetivo:
Aplicar un proceso ETL completo en Python usando Pandas:

1. Extraer datos desde una fuente externa (CSV)
2. Transformar los datos (limpieza, tipos, análisis básico)
3. Cargar los datos procesados en un nuevo archivo

##Requerimientos:

##1. Extracción (Extract)
* Cargar el dataset desde la URL usando pandas.
* Asignar nombres de columnas adecuados.

In [1]:
#Cargar el dataset desde la URL usando pandas
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [9]:
#Asignar nombres de columnas adecuados.
df = pd.read_csv(url, header=None)
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

##2. Transformación (Transform)
Debe realizar al menos:

1. Verificar estructura (info, head)
2. Renombrar columnas
3. Validar datos nulos
4. Convertir tipos de datos si es necesario
5. Crear una nueva columna (ej: promedio de medidas)
6. Filtrar datos (ej: solo una especie)

In [15]:
#1. Verificar estructura (info, head)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   longitud_sepalo  150 non-null    float64
 1   ancho_sepalo     150 non-null    float64
 2   longitud_petalo  150 non-null    float64
 3   ancho_petalo     150 non-null    float64
 4   clase            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [14]:
df.head()

   longitud_sepalo  ancho_sepalo  longitud_petalo  ancho_petalo        clase
0              5.1           3.5              1.4           0.2  Iris-setosa
1              4.9           3.0              1.4           0.2  Iris-setosa
2              4.7           3.2              1.3           0.2  Iris-setosa
3              4.6           3.1              1.5           0.2  Iris-setosa
4              5.0           3.6              1.4           0.2  Iris-setosa

In [11]:
#2. Renombrar columnas
df.rename(columns={'sepal_length': 'longitud_sepalo', 'sepal_width': 'ancho_sepalo', 'petal_length': 'longitud_petalo', 'petal_width': 'ancho_petalo', 'class': 'clase'}, inplace=True)

In [13]:
#3. Validar datos nulos
df.isnull().sum()

longitud_sepalo    0
ancho_sepalo       0
longitud_petalo    0
ancho_petalo       0
clase              0
dtype: int64

In [16]:
#4. Convertir tipos de datos si es necesario
df.dtypes

longitud_sepalo    float64
ancho_sepalo       float64
longitud_petalo    float64
ancho_petalo       float64
clase               object
dtype: object

In [18]:
#5. Crea una nueva columna (ej.promedio de medidas)
df['promedio_medidas'] = (df['longitud_sepalo'] + df['ancho_sepalo'] + df['longitud_petalo'] + df['ancho_petalo']) / 4

In [20]:
# 6. Filtrar datos (ej: solo una especie)
df_setosa = df[df['clase'] == 'Iris-setosa']
df_setosa.head()

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,clase,promedio_medidas
0,5.1,3.5,1.4,0.2,Iris-setosa,2.550
1,4.9,3.0,1.4,0.2,Iris-setosa,2.375
2,4.7,3.2,1.3,0.2,Iris-setosa,2.350
3,4.6,3.1,1.5,0.2,Iris-setosa,2.350
4,5.0,3.6,1.4,0.2,Iris-setosa,2.550

##3. Carga (Load)

1. Guardar el dataset limpio en un nuevo archivo CSV
2. Mostrar resumen estadístico

In [22]:
#1. Guardar el dataset limpio en un nuevo archivo CSV
df.to_csv('iris_cleaned.csv', index=False)

In [23]:
#2. Mostrar resumen estadistico
df.describe()

,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,promedio_medidas
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667,3.463667
std,0.828066,0.433594,1.764420,0.763161,0.782037
min,4.300000,2.000000,1.000000,0.100000,2.100000
25%,5.100000,2.800000,1.600000,0.300000,2.675000
50%,5.800000,3.000000,4.350000,1.300000,3.575000
75%,6.400000,3.300000,5.100000,1.800000,4.062500
max,7.900000,4.400000,6.900000,2.500000,5.100000